image: elixir:1.5

variables:
  MIX_ENV: "test"

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test

test:
  script:
     - mix test
     - mix credo --strict
     - mix inch --pedantic

after_script:
  - mix inch.report
